variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - proof
  - build
  - test

proof-job:
  stage: proof
  script:
    - echo "Hello"
    - make -C CompCert -j
    - make -j 4 proof

build-job:
  stage: build
  script:
    - echo "Hello"
    - make -j 4
  artifacts:
    paths:
      - ./_build/
      - ./velus

test-job:
  stage: test
  script:
    - cd tests/
    - ./runtests.sh
