variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - ./CompCert/

stages:
  - CompCert
  - proof
  - build
  - test

CompCert-job:
  stage: CompCert
  script:
    - echo "Hello"
    - test -f "./CompCert/Makefile.config" || (cd CompCert/ && ./configure x86_64-linux)
    - make -C CompCert -j

proof-job:
  stage: proof
  artifacts:
    untracked: true
    paths:
      - ./src/
  script:
    - echo "Hello"
    - rm -f .depend
    - ./configure x86_64-linux --velus-only
    - TERM=xterm-mono make clean
    - TERM=xterm-mono make -j 4 proof

build-job:
  stage: build
  artifacts:
    paths:
      - ./_build/
      - ./velus
  script:
    - echo "Hello"
    - make -j 4

test-job:
  stage: test
  script:
    - cd tests/
    - ./runtests.sh
