variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - CompCert
  - proof
  - build
  - test

CompCert-job:
  stage: CompCert
  cache:
    paths:
      - ./CompCert/
  script:
    - echo "Hello"
    - test -f "./CompCert/Makefile.config" || ./configure x86_64-linux
    - make -C CompCert -j

proof-job:
  stage: proof
  artifacts:
    untracked: true
    paths:
      - ./src/
  script:
    - echo "Hello"
    - make -j 4 proof

build-job:
  stage: build
  artifacts:
    paths:
      - ./_build/
      - ./velus
  script:
    - echo "Hello"
    - make -j 4

test-job:
  stage: test
  script:
    - cd tests/
    - ./runtests.sh
