variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello"
    - ./configure ia32-linux
    - make -C CompCert -j
    - make -j 4
  artifacts:
    paths:
      - ./_build/
      - ./velus

test-job:
  stage: test
  script:
    - cd tests/
    - ./runtests.sh
