variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-job:
  stage: build
  only:
    - basile-thesis
  script:
    - echo "Hello"
    - ./configure ia32-linux
    - make -C CompCert -j
    - make -j
