variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-job:
  stage: build
  only:
    - basile-thesis
  script:
    - echo "Hello"
    - ./configure ia32-linux
    - make -C CompCert -j
    - make -j

test-job:
  stage: test
  only:
    - basile-thesis
  allow_failure:
    exit_codes: 1
  variables:
    GIT_CLEAN_FLAGS: none
  script:
    - cd tests/
    - ./runtests.sh
