#!/bin/sh

SRCFILE=${1:?"Source file not given"}
NODE=${2:-main}
NAME=${SRCFILE%.*}

./velus -dsnlustre -dstc -dobc -dclight -sync -main $NODE $SRCFILE && \
CompCert/ccomp -Wl,-emain_sync -stdlib CompCert/runtime $NAME.sync.c $NAME.s
