.PHONY: run clean cleanall

run:
	./runtests.sh

clean:
	-@rm -rf \
	   *.parsed.lus *.nolast.lus *.noauto.lus *.noswitch.lus *.nolocal.lus \
	   *.n.lus *.stc *.obc \
	   *.light.c *.s *.exe

cleanall: clean

