# File generated by CompCert 3.5
# Command line: ok_alias.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	1
	.data
	.align	3
	.globl	_u$
_u$:
	.space	1
	.data
	.align	3
	.globl	_w$
_w$:
	.space	1
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_z$
_z$:
	.space	1
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	movzbl	0(%ecx), %edx
	xorl	%eax, %eax
	movb	%al, 0(%ecx)
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	movl	$1, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$wrong$step
_fun$wrong$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 20(%esp)
	movl	%ebx, 24(%esp)
	movl	%esi, 28(%esp)
	movl	%edi, 32(%esp)
	movl	12(%eax), %edi
	movl	8(%eax), %esi
	movl	4(%eax), %edx
	movl	0(%eax), %ebx
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	cmpl	$0, %esi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %esi
	cmpl	$0, %edi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 16(%esp)
	movl	%eax, 12(%esp)
	movl	%esi, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%ebx, 0(%esp)
	call	_fun$f$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movl	24(%esp), %ebx
	movl	28(%esp), %esi
	movl	32(%esp), %edi
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$wrong$reset
_fun$wrong$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 4(%esp)
	movl	0(%eax), %ecx
	movl	%ecx, 0(%esp)
	call	_fun$f$reset
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 16(%esp)
	movl	%ebx, 20(%esp)
	movl	%esi, 24(%esp)
	movl	%edi, 28(%esp)
	leal	_self$, %ecx
	movl	%ecx, 0(%esp)
	call	_fun$wrong$reset
L100:
	movzbl	_w$, %edx
	movzbl	_x$, %esi
	movzbl	_z$, %edi
	leal	_self$, %ebx
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	cmpl	$0, %esi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %esi
	cmpl	$0, %edi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 12(%esp)
	movl	%esi, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%ebx, 0(%esp)
	call	_fun$wrong$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _u$
	jmp	L100
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
