# File generated by CompCert 3.5
# Command line: ok_constfbyck.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_ck$
_ck$:
	.space	1
	.text
	.align	4
	.globl _fun$test$step
_fun$test$step:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	4(%eax), %ecx
	movl	0(%eax), %ebx
	cmpl	$0, %ecx
	je	L100
	movzbl	0(%ebx), %edx
	movzbl	1(%ebx), %eax
	andl	%eax, %edx
	movl	$1, %eax
	movb	%al, 0(%ebx)
	xorl	%eax, %eax
	movb	%al, 1(%ebx)
	jmp	L101
L100:
	movl	$1, %edx
L101:
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	4(%esp), %ebx
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$test$reset
_fun$test$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %edx
	xorl	%eax, %eax
	movb	%al, 0(%edx)
	movl	$1, %eax
	movb	%al, 1(%edx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 8(%esp)
	leal	_self$, %ecx
	movl	%ecx, 0(%esp)
	call	_fun$test$reset
L102:
	movzbl	_ck$, %eax
	leal	_self$, %edx
	cmpl	$0, %eax
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 4(%esp)
	movl	%edx, 0(%esp)
	call	_fun$test$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L102
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
