# File generated by CompCert 3.5
# Command line: ok_clockedconstfby2.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_w$
_w$:
	.space	1
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.text
	.align	4
	.globl _fun$g$step
_fun$g$step:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	0(%eax), %edx
	movzbl	0(%edx), %ebx
	cmpl	$0, %ebx
	sete	%cl
	movzbl	%cl, %ecx
	movb	%cl, 0(%edx)
	cmpl	$0, %ebx
	setne	%al
	movzbl	%al, %eax
	movl	4(%esp), %ebx
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$g$reset
_fun$g$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	movl	%edi, 24(%esp)
	movl	%ebp, 28(%esp)
	movl	8(%eax), %edi
	movl	4(%eax), %esi
	movl	0(%eax), %ebx
	leal	1(%ebx), %edx
	cmpl	$0, %esi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %ebp
	movzbl	0(%ebx), %ecx
	cmpl	$0, %ecx
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 8(%esp)
	movl	%ebp, 4(%esp)
	movl	%edx, 0(%esp)
	call	_fun$g$step
	movl	%eax, %edx
	cmpl	$0, %esi
	je	L100
	cmpl	$0, %edi
	sete	%al
	movzbl	%al, %eax
	movb	%al, 0(%ebx)
L100:
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	16(%esp), %ebx
	movl	20(%esp), %esi
	movl	24(%esp), %edi
	movl	28(%esp), %ebp
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 4(%esp)
	movl	0(%eax), %edx
	xorl	%ecx, %ecx
	movb	%cl, 0(%edx)
	leal	1(%edx), %edx
	movl	%edx, 0(%esp)
	call	_fun$g$reset
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	leal	_self$, %eax
	movl	%eax, 0(%esp)
	call	_fun$f$reset
L101:
	movzbl	_x$, %ecx
	movzbl	_y$, %ebx
	leal	_self$, %esi
	cmpl	$0, %ecx
	setne	%dl
	movzbl	%dl, %edx
	cmpl	$0, %ebx
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$f$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _w$
	jmp	L101
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
