# File generated by CompCert 3.5
# Command line: ok_ckonck2b.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	1
	.data
	.align	3
	.globl	_z$
_z$:
	.space	1
	.data
	.align	3
	.globl	_w$
_w$:
	.space	1
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_a$
_a$:
	.space	1
	.data
	.align	3
	.globl	_b$
_b$:
	.space	1
	.data
	.align	3
	.globl	_c$
_c$:
	.space	1
	.data
	.align	3
	.globl	_d$
_d$:
	.space	1
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	%edi, 12(%esp)
	movl	%ebp, 16(%esp)
	movl	20(%eax), %eax
	movl	%eax, 24(%esp)
	movl	0(%esp), %eax
	movl	16(%eax), %ebp
	movl	12(%eax), %edi
	movl	8(%eax), %esi
	movl	4(%eax), %ebx
	movl	0(%eax), %edx
	movzbl	0(%edx), %ecx
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movb	%al, 0(%ebx)
	movl	$1, %ecx
	movb	%cl, 0(%edx)
	xorl	%edx, %edx
	movb	%dl, 2(%ebx)
	xorl	%eax, %eax
	movb	%al, 3(%ebx)
	cmpl	$0, %edi
	je	L100
	cmpl	$0, %esi
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 1(%ebx)
	cmpl	$0, %ebp
	je	L101
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 2(%ebx)
	movl	24(%esp), %ecx
	cmpl	$0, %ecx
	je	L101
	cmpl	$0, %edx
	setne	%cl
	movzbl	%cl, %ecx
	movb	%cl, 3(%ebx)
	jmp	L101
L100:
	xorl	%edx, %edx
	movb	%dl, 1(%ebx)
L101:
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	movl	12(%esp), %edi
	movl	16(%esp), %ebp
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$60, %esp
	.cfi_adjust_cfa_offset	60
	leal	64(%esp), %eax
	movl	%eax, 24(%esp)
	movl	%ebx, 28(%esp)
	movl	%esi, 32(%esp)
	movl	%edi, 36(%esp)
	movl	%ebp, 40(%esp)
	leal	_self$, %ecx
	movl	%ecx, 0(%esp)
	call	_fun$f$reset
L102:
	movzbl	_a$, %ecx
	movzbl	_b$, %edx
	movzbl	_c$, %ebp
	movzbl	_d$, %esi
	leal	_self$, %ebx
	leal	56(%esp), %eax
	movl	%eax, 48(%esp)
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %edi
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	cmpl	$0, %ebp
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %ebp
	cmpl	$0, %esi
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 20(%esp)
	movl	%ebp, 16(%esp)
	movl	%edx, 12(%esp)
	movl	%edi, 8(%esp)
	movl	48(%esp), %ecx
	movl	%ecx, 4(%esp)
	movl	%ebx, 0(%esp)
	call	_fun$f$step
	movzbl	56(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _z$
	movzbl	57(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _w$
	movzbl	58(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _x$
	movzbl	59(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L102
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
