# File generated by CompCert 3.5
# Command line: ok_clockedcapp.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	%edi, 12(%esp)
	movl	8(%eax), %esi
	movl	4(%eax), %ebx
	movl	0(%eax), %edi
	movzbl	0(%edi), %eax
	cmpl	$0, %eax
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 1(%ebx)
	cmpl	$0, %edx
	sete	%cl
	movzbl	%cl, %ecx
	movb	%cl, 0(%edi)
	movzbl	1(%ebx), %ecx
	cmpl	$0, %ecx
	jne	L100
	xorl	%edx, %edx
	movb	%dl, 0(%ebx)
	jmp	L101
L100:
	cmpl	$0, %esi
	setne	%al
	movzbl	%al, %eax
	movb	%al, 0(%ebx)
L101:
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	movl	12(%esp), %edi
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$g$step
_fun$g$step:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	12(%eax), %edx
	movl	8(%eax), %ecx
	movl	0(%eax), %ebx
	cmpl	$0, %edx
	je	L102
	movzbl	0(%ebx), %edx
	cmpl	$0, %ecx
	sete	%al
	movzbl	%al, %eax
	movb	%al, 0(%ebx)
	jmp	L103
L102:
	xorl	%edx, %edx
L103:
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	4(%esp), %ebx
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$g$reset
_fun$g$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$h$step
_fun$h$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 16(%esp)
	movl	%ebx, 20(%esp)
	movl	%esi, 24(%esp)
	movl	%edi, 28(%esp)
	movl	%ebp, 32(%esp)
	movl	4(%eax), %ebx
	movl	0(%eax), %esi
	cmpl	$0, %ebx
	je	L104
	leal	40(%esp), %eax
	movl	$1, %ecx
	movl	%ecx, 8(%esp)
	movl	%eax, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$f$step
	movzbl	40(%esp), %eax
	movzbl	41(%esp), %edx
	jmp	L105
L104:
	xorl	%eax, %eax
	xorl	%edx, %edx
L105:
	leal	1(%esi), %esi
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %edi
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %ebp
	cmpl	$0, %ebx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 12(%esp)
	movl	%ebp, 8(%esp)
	movl	%edi, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$g$step
	cmpl	$0, %ebx
	jne	L106
	xorl	%eax, %eax
L106:
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movl	20(%esp), %ebx
	movl	24(%esp), %esi
	movl	28(%esp), %edi
	movl	32(%esp), %ebp
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$h$reset
_fun$h$reset:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	0(%eax), %ebx
	movl	%ebx, 0(%esp)
	call	_fun$f$reset
	leal	1(%ebx), %eax
	movl	%eax, 0(%esp)
	call	_fun$g$reset
	movl	8(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 8(%esp)
	leal	_self$, %ecx
	movl	%ecx, 0(%esp)
	call	_fun$h$reset
L107:
	movzbl	_x$, %eax
	leal	_self$, %edx
	cmpl	$0, %eax
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 4(%esp)
	movl	%edx, 0(%esp)
	call	_fun$h$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L107
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
