# File generated by CompCert 3.5
# Command line: ok_depout5.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	1
	.data
	.align	3
	.globl	_w$
_w$:
	.space	1
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_b$
_b$:
	.space	1
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	%edi, 12(%esp)
	movl	8(%eax), %edi
	movl	4(%eax), %ebx
	movl	0(%eax), %esi
	movzbl	0(%esi), %ecx
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movb	%al, 0(%ebx)
	cmpl	$0, %edi
	setne	%al
	movzbl	%al, %eax
	movb	%al, 0(%esi)
	movzbl	0(%ebx), %edx
	cmpl	$0, %edx
	jne	L100
	xorl	%eax, %eax
	movb	%al, 1(%ebx)
	jmp	L101
L100:
	movl	$1, %ecx
	movb	%cl, 1(%ebx)
L101:
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	movl	12(%esp), %edi
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$g$step
_fun$g$step:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	12(%eax), %edx
	movl	8(%eax), %ecx
	movl	4(%eax), %ebx
	cmpl	$0, %ecx
	jne	L102
	xorl	%eax, %eax
	movb	%al, 0(%ebx)
	xorl	%edx, %edx
	jmp	L103
L102:
	movl	$1, %ecx
	movb	%cl, 0(%ebx)
L103:
	movzbl	0(%ebx), %eax
	cmpl	$0, %eax
	jne	L104
	xorl	%ecx, %ecx
	movb	%cl, 1(%ebx)
	jmp	L105
L104:
	cmpl	$0, %edx
	setne	%cl
	movzbl	%cl, %ecx
	movb	%cl, 1(%ebx)
L105:
	movl	4(%esp), %ebx
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$g$reset
_fun$g$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$main$step
_fun$main$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 16(%esp)
	movl	%ebx, 20(%esp)
	movl	%esi, 24(%esp)
	movl	%edi, 28(%esp)
	movl	%ebp, 32(%esp)
	movl	8(%eax), %ecx
	movl	4(%eax), %ebx
	movl	0(%eax), %esi
	leal	40(%esp), %edx
	cmpl	$0, %ecx
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$f$step
	movzbl	40(%esp), %ecx
	movzbl	41(%esp), %edi
	leal	1(%esi), %esi
	leal	42(%esp), %edx
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %ebp
	cmpl	$0, %edi
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 12(%esp)
	movl	%ebp, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$g$step
	movzbl	42(%esp), %edx
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 0(%ebx)
	movzbl	43(%esp), %ecx
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movb	%al, 1(%ebx)
	movl	20(%esp), %ebx
	movl	24(%esp), %esi
	movl	28(%esp), %edi
	movl	32(%esp), %ebp
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$main$reset
_fun$main$reset:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	0(%eax), %ebx
	movl	%ebx, 0(%esp)
	call	_fun$f$reset
	leal	1(%ebx), %eax
	movl	%eax, 0(%esp)
	call	_fun$g$reset
	movl	8(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	leal	_self$, %eax
	movl	%eax, 0(%esp)
	call	_fun$main$reset
L106:
	movzbl	_b$, %edx
	leal	_self$, %ebx
	leal	24(%esp), %esi
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 8(%esp)
	movl	%esi, 4(%esp)
	movl	%ebx, 0(%esp)
	call	_fun$main$step
	movzbl	24(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _w$
	movzbl	25(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _x$
	jmp	L106
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
