# File generated by CompCert 3.5
# Command line: ok_fbyfby.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_i$
_i$:
	.space	1
	.text
	.align	4
	.globl _fun$fbyfby$step
_fun$fbyfby$step:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	4(%eax), %esi
	movl	0(%eax), %ebx
	movzbl	0(%ebx), %edx
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 0(%esi)
	movzbl	1(%ebx), %eax
	cmpl	$0, %eax
	setne	%dl
	movzbl	%dl, %edx
	movb	%dl, 1(%esi)
	cmpl	$0, %edx
	setne	%cl
	movzbl	%cl, %ecx
	movb	%cl, 0(%ebx)
	movzbl	0(%esi), %ecx
	cmpl	$0, %ecx
	sete	%cl
	movzbl	%cl, %ecx
	movb	%cl, 1(%ebx)
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$fbyfby$reset
_fun$fbyfby$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %edx
	movl	$1, %eax
	movb	%al, 0(%edx)
	movl	$1, %eax
	movb	%al, 1(%edx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	leal	_self$, %eax
	movl	%eax, 0(%esp)
	call	_fun$fbyfby$reset
L100:
	movzbl	_i$, %edx
	leal	_self$, %ebx
	leal	24(%esp), %esi
	cmpl	$0, %edx
	setne	%al
	movzbl	%al, %eax
	movl	%eax, 8(%esp)
	movl	%esi, 4(%esp)
	movl	%ebx, 0(%esp)
	call	_fun$fbyfby$step
	movzbl	24(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _x$
	movzbl	25(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L100
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
