# File generated by CompCert 3.5
# Command line: ok_fbymultick.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_x$
_x$:
	.space	1
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_a$
_a$:
	.space	1
	.data
	.align	3
	.globl	_b$
_b$:
	.space	1
	.text
	.align	4
	.globl _fun$fbyfby$step
_fun$fbyfby$step:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	12(%eax), %edx
	movl	8(%eax), %ecx
	movl	4(%eax), %esi
	movl	0(%eax), %ebx
	cmpl	$0, %ecx
	je	L100
	movzbl	0(%ebx), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, 0(%esi)
	xorl	%ecx, %ecx
	movb	%cl, 0(%ebx)
	jmp	L101
L100:
	xorl	%ecx, %ecx
	movb	%cl, 0(%esi)
L101:
	cmpl	$0, %edx
	je	L102
	movzbl	1(%ebx), %ecx
	cmpl	$0, %ecx
	setne	%al
	movzbl	%al, %eax
	movb	%al, 1(%esi)
	movl	$1, %edx
	movb	%dl, 1(%ebx)
	jmp	L103
L102:
	xorl	%ecx, %ecx
	movb	%cl, 1(%esi)
L103:
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$fbyfby$reset
_fun$fbyfby$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %edx
	movl	$1, %eax
	movb	%al, 0(%edx)
	xorl	%eax, %eax
	movb	%al, 1(%edx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 16(%esp)
	movl	%ebx, 20(%esp)
	movl	%esi, 24(%esp)
	movl	%edi, 28(%esp)
	leal	_self$, %eax
	movl	%eax, 0(%esp)
	call	_fun$fbyfby$reset
L104:
	movzbl	_a$, %eax
	movzbl	_b$, %edx
	leal	_self$, %esi
	leal	32(%esp), %ebx
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movl	%eax, %edi
	cmpl	$0, %edx
	setne	%dl
	movzbl	%dl, %edx
	movl	%edx, 12(%esp)
	movl	%edi, 8(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$fbyfby$step
	movzbl	32(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _x$
	movzbl	33(%esp), %eax
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L104
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
