# File generated by CompCert 3.5
# Command line: ok_whenmulti2.lus
	.data
	.align	3
	.globl	_self$
_self$:
	.space	2
	.data
	.align	3
	.globl	_y$
_y$:
	.space	1
	.data
	.align	3
	.globl	_a$
_a$:
	.space	1
	.data
	.align	3
	.globl	_b$
_b$:
	.space	1
	.text
	.align	4
	.globl _fun$f$step
_fun$f$step:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	8(%eax), %edx
	movl	4(%eax), %esi
	movl	0(%eax), %ebx
	cmpl	$0, %edx
	setne	%cl
	movzbl	%cl, %ecx
	movb	%cl, 0(%esi)
	movzbl	0(%ebx), %eax
	cmpl	$0, %eax
	setne	%cl
	movzbl	%cl, %ecx
	movb	%cl, 1(%esi)
	cmpl	$0, %edx
	sete	%dl
	movzbl	%dl, %edx
	movb	%dl, 0(%ebx)
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$f$reset
_fun$f$reset:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	movl	0(%eax), %ecx
	xorl	%edx, %edx
	movb	%dl, 0(%ecx)
	addl	$12, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$multimerge$step
_fun$multimerge$step:
	.cfi_startproc
	subl	$44, %esp
	.cfi_adjust_cfa_offset	44
	leal	48(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	movl	%edi, 24(%esp)
	movl	%ebp, 28(%esp)
	movl	8(%eax), %esi
	movl	4(%eax), %ebp
	movl	0(%eax), %edi
	leal	32(%esp), %edx
	cmpl	$0, %esi
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%edi, 0(%esp)
	call	_fun$f$step
	movzbl	32(%esp), %ebx
	leal	1(%edi), %edx
	leal	34(%esp), %edi
	cmpl	$0, %esi
	sete	%al
	movzbl	%al, %eax
	movl	%eax, 8(%esp)
	movl	%edi, 4(%esp)
	movl	%edx, 0(%esp)
	call	_fun$f$step
	cmpl	$0, %ebp
	jne	L100
	movl	%esi, %ebx
L100:
	cmpl	$0, %ebx
	setne	%al
	movzbl	%al, %eax
	movl	16(%esp), %ebx
	movl	20(%esp), %esi
	movl	24(%esp), %edi
	movl	28(%esp), %ebp
	addl	$44, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _fun$multimerge$reset
_fun$multimerge$reset:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	0(%eax), %ebx
	movl	%ebx, 0(%esp)
	call	_fun$f$reset
	leal	1(%ebx), %eax
	movl	%eax, 0(%esp)
	call	_fun$f$reset
	movl	8(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.text
	.align	4
	.globl _main_proved
_main_proved:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %eax
	movl	%eax, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	%esi, 20(%esp)
	leal	_self$, %eax
	movl	%eax, 0(%esp)
	call	_fun$multimerge$reset
L101:
	movzbl	_a$, %ecx
	movzbl	_b$, %ebx
	leal	_self$, %esi
	cmpl	$0, %ecx
	setne	%dl
	movzbl	%dl, %edx
	cmpl	$0, %ebx
	setne	%cl
	movzbl	%cl, %ecx
	movl	%ecx, 8(%esp)
	movl	%edx, 4(%esp)
	movl	%esi, 0(%esp)
	call	_fun$multimerge$step
	cmpl	$0, %eax
	setne	%al
	movzbl	%al, %eax
	movb	%al, _y$
	jmp	L101
	.cfi_endproc
	.text
	.align	4
	.globl _main
_main:
	.cfi_startproc
	subl	$12, %esp
	.cfi_adjust_cfa_offset	12
	leal	16(%esp), %eax
	movl	%eax, 0(%esp)
	call	_main_proved
	movl	%ebx, %eax
	addl	$12, %esp
	ret
	.cfi_endproc
	.section __IMPORT,__pointers,non_lazy_symbol_pointers
