
let map_token (Specif.Coq_existT (tok, l) : FrustreParser.Aut.GramDefs.token) =
  let loc l = (Obj.magic l : FrustreAst.astloc) in
  let open FrustreParser.Aut.GramDefs in
  match tok with
  | ASSERT't     -> (FrustreParser2.ASSERT     (loc l), loc l)
  | AND't        -> (FrustreParser2.AND        (loc l), loc l)
  | BOOL't       -> (FrustreParser2.BOOL       (loc l), loc l)
  | COLONCOLON't -> (FrustreParser2.COLONCOLON (loc l), loc l)
  | COLON't      -> (FrustreParser2.COLON      (loc l), loc l)
  | COMMA't      -> (FrustreParser2.COMMA      (loc l), loc l)
  | CONSTANT't   -> let v = (Obj.magic l :
                              FrustreAst.constant * FrustreAst.astloc) in
                   (FrustreParser2.CONSTANT  v      , snd v)
  | DOT't        -> (FrustreParser2.DOT        (loc l), loc l)
  | ELSE't       -> (FrustreParser2.ELSE       (loc l), loc l)
  | EOF't        -> (FrustreParser2.EOF        (loc l), loc l)
  | EQ't         -> (FrustreParser2.EQ         (loc l), loc l)
  | FALSE't      -> (FrustreParser2.FALSE      (loc l), loc l)
  | FBY't        -> (FrustreParser2.FBY        (loc l), loc l)
  | FLOAT32't    -> (FrustreParser2.FLOAT32    (loc l), loc l)
  | FLOAT64't    -> (FrustreParser2.FLOAT64    (loc l), loc l)
  | FUNCTION't   -> (FrustreParser2.FUNCTION   (loc l), loc l)
  | GEQ't        -> (FrustreParser2.GEQ        (loc l), loc l)
  | GT't         -> (FrustreParser2.GT         (loc l), loc l)
  | IF't         -> (FrustreParser2.IF         (loc l), loc l)
  | INT16't      -> (FrustreParser2.INT16      (loc l), loc l)
  | INT32't      -> (FrustreParser2.INT32      (loc l), loc l)
  | INT64't      -> (FrustreParser2.INT64      (loc l), loc l)
  | INT8't       -> (FrustreParser2.INT8       (loc l), loc l)
  | LAND't       -> (FrustreParser2.LAND       (loc l), loc l)
  | LEQ't        -> (FrustreParser2.LEQ        (loc l), loc l)
  | LET't        -> (FrustreParser2.LET        (loc l), loc l)
  | LNOT't       -> (FrustreParser2.LNOT       (loc l), loc l)
  | LOR't        -> (FrustreParser2.LOR        (loc l), loc l)
  | LPAREN't     -> (FrustreParser2.LPAREN     (loc l), loc l)
  | LSL't        -> (FrustreParser2.LSL        (loc l), loc l)
  | LSR't        -> (FrustreParser2.LSR        (loc l), loc l)
  | LT't         -> (FrustreParser2.LT         (loc l), loc l)
  | LXOR't       -> (FrustreParser2.LXOR       (loc l), loc l)
  | MERGE't      -> (FrustreParser2.MERGE      (loc l), loc l)
  | MINUS't      -> (FrustreParser2.MINUS      (loc l), loc l)
  | MOD't        -> (FrustreParser2.MOD        (loc l), loc l)
  | NEQ't        -> (FrustreParser2.NEQ        (loc l), loc l)
  | NODE't       -> (FrustreParser2.NODE       (loc l), loc l)
  | NOT't        -> (FrustreParser2.NOT        (loc l), loc l)
  | ON't         -> (FrustreParser2.ON         (loc l), loc l)
  | ONOT't       -> (FrustreParser2.ONOT       (loc l), loc l)
  | OR't         -> (FrustreParser2.OR         (loc l), loc l)
  | PLUS't       -> (FrustreParser2.PLUS       (loc l), loc l)
  | RARROW't     -> (FrustreParser2.RARROW     (loc l), loc l)
  | RETURNS't    -> (FrustreParser2.RETURNS    (loc l), loc l)
  | RPAREN't     -> (FrustreParser2.RPAREN     (loc l), loc l)
  | SEMICOLON't  -> (FrustreParser2.SEMICOLON  (loc l), loc l)
  | SLASH't      -> (FrustreParser2.SLASH      (loc l), loc l)
  | STAR't       -> (FrustreParser2.STAR       (loc l), loc l)
  | TEL't        -> (FrustreParser2.TEL        (loc l), loc l)
  | THEN't       -> (FrustreParser2.THEN       (loc l), loc l)
  | TRUE't       -> (FrustreParser2.TRUE       (loc l), loc l)
  | UINT16't     -> (FrustreParser2.UINT16     (loc l), loc l)
  | UINT32't     -> (FrustreParser2.UINT32     (loc l), loc l)
  | UINT64't     -> (FrustreParser2.UINT64     (loc l), loc l)
  | UINT8't      -> (FrustreParser2.UINT8      (loc l), loc l)
  | VAR't        -> (FrustreParser2.VAR        (loc l), loc l)
  | VAR_NAME't   -> let v = (Obj.magic l :
                                FrustreAst.ident * FrustreAst.astloc) in
                   (FrustreParser2.VAR_NAME    v      , snd v)
  | WHEN't       -> (FrustreParser2.WHEN       (loc l), loc l)
  | WHENOT't     -> (FrustreParser2.WHENOT     (loc l), loc l)
  | XOR't        -> (FrustreParser2.XOR        (loc l), loc l)

